@startuml

skinparam componentStyle uml2

package "'TeamsAndUsers' Aggregate" <<Rectangle>> {
	class Team <<(A,#fffab8) Aggregate Root>> {
		String name
		MemberId leader
		List<MemberId> members
		Integer teamScore
		TeamId id
	}
	class Member <<(A,#fffab8) Aggregate Root>> {
		String name
		String null
		String password
		Role role
		int individualScore
		List<RewardId> unlockedRewards
		MemberId id
	}
	class Feedback <<(A,#fffab8) Aggregate Root>> {
		String message
		Date date
		MemberId givenBy
		MemberId receivedBy
		TaskId relatedTask
		FeedbackId id
	}
	class TeamId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
	class FeedbackId <<(V,DarkSeaGreen) Value Object>> {
		int id
	}
	class Role <<(V,DarkSeaGreen) Value Object>> {
	}
	enum Leader {
	}
	enum Member {
	}
	class TeamsAndUsersService <<(S,DarkSeaGreen) Service>> {
		void createTeam(TeamId teamId, null null)
		void addMember(TeamId teamId, MemberId memberId, Role role)
		List<Reward> getUnlockedRewards(MemberId memberId)
		int getScore(MemberId memberId)
		List<Feedback> getReceivedFeedbacks(MemberId memberId)
	}
}
Feedback --> FeedbackId : id
legend left
  This bounded context implements the subdomain 'TeamsAndUsers'.
end legend


@enduml
